# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/

# We are using a configuration for each submodule so they run at a different time
# to avoid multiple PRs running CI and SauceLabs.

version: 2
updates:
  - package-ecosystem: "gitsubmodule" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "18:00" # UTC time
    groups:
      submodules:
        patterns:
        - "gutenberg"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
    groups:
      submodules:
        patterns:
        - "jetpack"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:00"
    groups:
      submodules:
        patterns:
        - "block-experiments"