# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/

# We are using a configuration for each submodule so they run at a different time
# to avoid multiple PRs running CI and SauceLabs.

version: 2
updates:
  - package-ecosystem: "gitsubmodule" # See documentation for possible values
    directory: "/gutenberg" # Location of package manifests
    schedule:
      interval: "daily"
      time: "12:00" # UTC time
  - package-ecosystem: "gitsubmodule"
    directory: "/jetpack"
    schedule:
      interval: "daily"
      time: "14:00"
  - package-ecosystem: "gitsubmodule"
    directory: "/block-experiments"
    schedule:
      interval: "daily"
      time: "16:00"