name: sync-android-pr
on:
  pull_request:
    types: [labeled]
jobs:
  build:
    if: ${{ github.event.label.name == 'sync-android-pr' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Create a WordPress-Android PR to build WordPress-Android with your Current Gutenberg Mobile Changes.
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          npm run sync-pr:android -- "--pr=$PR_NUMBER --sha=$PR_HEAD_SHA"
