name: sync-android
on:
  pull_request:
    types: [labeled]
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a WordPress-Android (WPA) PR containing changes from a Gutenberg Mobile (GBM) PR.
        env:
          PR: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          npm run sync:android -- "--pr=$PR"
        if: ${{ github.event_name == 'pull_request' && github.event.label.name == 'sync:android' }}
      - name: Create a WordPress-Android (WPA) PR containing changes from a Gutenberg Mobile (GBM) Tag.
        env:
          TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          npm run sync:android -- "--tag=$TAG"
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}